---
# Copyright (c) 2020, 2023 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: Patch Oracle Database out-of-place
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  vars:
    database_ocid: "ocid1.database.oc1..."
    target_db_home_ocid: "ocid1.dbhome.oc1..."

  tasks:
    - block: 

        - name: Patch database by moving to a new Oracle Home
          oci_database_database:
            # required
            database_id: "{{ database_ocid }}"
            db_home_id: "{{ target_db_home_ocid }}"
            
          register: database
        - debug:
              msg: "{{ database }}"
