---
- name: Get information about Cloud Exadata Infrastructures
  oracle.oci.oci_database_cloud_exadata_infrastructure_facts:
    compartment_id: "{{ compartment_ocid }}"
    region: "{{ region }}"
  register: exacs_infra

- name: Show raw output (debug)
  debug:
    var: exacs_infra
