- name: List ExaCS VM Cluster OS updates
  oracle.oci.oci_database_vm_cluster_update_facts:
    compartment_id: "{{ compartment_id }}"
    vm_cluster_id: "{{ item.id }}"
    region: "{{ region }}"
  loop: "{{ vm_clusters }}"
  register: os_updates
  
- name: Show OS updates found for each VM Cluster
  debug:
    msg: "{{ item.ansible_facts.vm_cluster_updates }}"
  loop: "{{ os_updates.results }}"
