- name: List ExaCS VM Cluster GI patches
  oracle.oci.oci_database_vm_cluster_patch_facts:
    compartment_id: "{{ compartment_id }}"
    vm_cluster_id: "{{ item.id }}"
    region: "{{ region }}"
  loop: "{{ vm_clusters }}"
  register: gi_patches

- name: Show GI patches found for each VM Cluster
  debug:
    msg: "{{ item.ansible_facts.vm_cluster_patches }}"
  loop: "{{ gi_patches.results }}"
