---
- name: Get ExaCS infrastructure facts (diagnostic)
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - "../../inventories/exacs/group_vars/all.yml"

  roles:
    - diagnostic
