---
- name: Get ExaCS infrastructure facts (diagnostic)
  hosts: all
  gather_facts: false

  tasks:
    - name: Get ExaCS infra info
      import_tasks: ../../roles/diagnostic/tasks/getExaCSInfra.yml

