---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: List bucket facts
      oci_object_storage_bucket_facts:
         namespace_name: 'frlzmy5hrkeg'
         compartment_id: 'ocid1.compartment.oc1...'
         region: "eu-frankfurt-1"
      register: result
    - name: Dump result
      debug: 
        msg: 'Bucket name: {{item.name}}'
      loop: "{{ result.buckets }}"


