---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: List bucket in Frankfurt region
      oci_object_storage_bucket_facts:
         config_profile_name: "PROFILE1"
         namespace_name: 'frxfz3gch4zb'
         compartment_id: 'ocid1.compartment.oc1...'
         region: "eu-frankfurt-1"
      register: result
    - name: Dump result
      debug: 
        msg: 'Bucket name: {{item.name}}'
      loop: "{{ result.buckets }}"

    - name: List bucket in Amsterdam region
      oci_object_storage_bucket_facts:
         config_profile_name: "PROFILE1"
         namespace_name: 'frxfz3gch4zb'
         compartment_id: 'ocid1.compartment.oc1...'
         region: "eu-amsterdam-1"
      register: result
    - name: Dump result
      debug: 
        msg: 'Bucket name: {{item.name}}'
      loop: "{{ result.buckets }}"

