---
# Copyright (c) 2020, 2023 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: Restart an Oracle PDB
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  vars:
    pluggable_database_ocid: "ocid1.pluggabledatabase.oc1..."

  tasks:
    - block: 

        - name: Stop a PDB
          oci_database_pluggable_database_actions:
            # required
            pluggable_database_id: "{{ pluggable_database_ocid }}"
            action: stop
            
          register: pdb
        - debug:
              msg: "{{ pdb }}"

        - name: Start a PDB
          oci_database_pluggable_database_actions:
            # required
            pluggable_database_id: "{{ pluggable_database_ocid }}"
            action: start
            
          register: pdb
        - debug:
              msg: "{{ pdb }}"
