---
# Copyright (c) 2020, 2023 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: Restart an ExaCS VM Cluster DB Node
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  vars:
    db_node_ocid: "ocid1.dbnode.oc1..."

  tasks:
    - block: 

        - name: Stop VM Cluster DB Node
          oci_database_db_node_actions:
            # required
            db_node_id: "{{ db_node_ocid }}"
            action: stop
            
          register: dbnode
        - debug:
              msg: "{{ dbnode }}"

        - name: Start VM Cluster DB Node
          oci_database_db_node_actions:
            # required
            db_node_id: "{{ db_node_ocid }}"
            action: start
            
          register: dbnode
        - debug:
              msg: "{{ dbnode }}"
