---
# Copyright (c) 2020, 2023 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.

- name: Create Oracle Database
  hosts: localhost
  collections:
    - oracle.oci
  connection: local
  vars:
    db_home_ocid: "ocid1.dbhome.oc1..."

  tasks:
    - block: 

        - name: Create database with source = NONE
          oci_database_database:
            # required
            db_home_id: "{{ db_home_ocid }}"
            state: present
            force_create: yes
            database:
              # required
              admin_password: "WElcome12345##"

              # optional
              db_name: "PADBANS1"
              db_unique_name: "PADBANS1"
              pdb_name: "PADBANS1PDB1"
              tde_wallet_password: "WElcome12345##"
              character_set: "AL32UTF8"
              ncharacter_set: "AL16UTF16"
              db_workload: OLTP
              db_backup_config:
                # optional
                auto_backup_enabled: true
                recovery_window_in_days: 56
                auto_backup_window: SLOT_ONE
              sid_prefix: "PADBANS1"
            # optional
            db_version: "19.0.0.0"
            source: NONE
          register: database
        - debug:
              msg: "{{ database }}"

        - set_fact:
              container_database_ocid: "{{ database.database.id}}"

        - name: List the specific Database
          oci_database_database_facts:
            database_id: '{{ container_database_ocid }}'
          register: result

        - name: Assert that specified Db System was listed
          assert:
            that:
              - result.databases[0].id == container_database_ocid
        
        - name: Create pluggable database
          oci_database_pluggable_database:
            # required
            pdb_name: "PADBANS1PDB2"
            container_database_id: "{{ container_database_ocid }}"
            state: present
            force_create: yes

            # optional
            pdb_admin_password: "WElcome12345##"
            tde_wallet_password: "WElcome12345##"
            should_pdb_admin_account_be_locked: false
             
          register: pdb
        - debug:
              msg: "{{ pdb }}"